### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by chensivan** [cmpaul/oblique-strategies#1]
Hey, i really like your idea. But it is not work when I install it on my atom 1.2.4. No notification shows up either automatically or manually trigger.

**Comment by cmpaul** [comment]
Hi @chensivan ,

Have you tried restarting Atom after installing the package? Also, what OS are you on?

**Comment by chensivan** [comment]
hey, thanks for applying. I figured it out, it is because i modified my
notification package.
